### ISSUE TITLE
ApiException: 422 INVALID_FIELD

### ISSUE THREAD

**Issue by lbatteau** [datocms/generator-datocms-plugin#2]
Getting an `ApiException: 422 INVALID_FIELD` when generating a new plugin:

```
? Please insert the NPM package name for this new plugin (it must start with datocms-plugin-) xxx
? Please insert a human name for this plugin XXX
? Please insert a small description XXX
? What kind of plugin is it? (For more info see https://www.datocms.com/docs/plugins/introduction/#types-of-plugins) Field editor
? Which kind of fields is this plugin compatible with? String
? Please insert any configuration parameters this plugin requires (see https://www.datocms.com/docs/plugins/creating-a-new-plugin/#configuration-parameters) Received
? Please add some tags to make the plugin more discoverable (comma separated) field-editor, string-field
? Please add the homepage for this plugin https://github.com/YOUR-USER/xxx
? What's your name? Lukas Batteau
? What's your email? xxx
? Please select the preferred template React
? Would you like to add this plugin in development mode to one of your projects and start developing it right away? Yes
? In order to add this plugin to one of your projects we need you to sign in to DatoCMS. We'll open up a browser whenever you're ready! Yes
? On which project you would like to add this plugin in development mode? XXX

events.js:183
      throw er; // Unhandled 'error' event
      ^
ApiException: 422 INVALID_FIELD (details: {"field":"name","code":"VALIDATION_UNIQUENESS","recordType":"Plugin"})
    at /Users/lbatteau/node_modules/datocms-client/lib/Client.js:140:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by matjack1** [comment]
Hello, sorry I cannot replicate your issue, it works fine here :(

If you are still affected by this, can you please send me at support@datocms.com the DatoCMS project that you were using? So I'll try replicating the issue with your project.

I'm closing this for now as we need to continue over support.
