### ISSUE TITLE
Undefined is not iterable error when running the Yeoman command

### ISSUE THREAD

**Issue by NSpehler** [datocms/generator-datocms-plugin#7]
Hello,

I'm trying to run the plugin generator without luck. Here's the error I'm getting when running `npx -p yo -p generator-datocms-plugin -c 'yo datocms-plugin'` from my new plugin directory:

```
nspehler@nspehler datocms-plugin-gallery-hero-image % npx -p yo -p generator-datocms-plugin -c 'yo datocms-plugin'
/Users/nspehler/.npm/_npx/89d7643beec8fcc5/node_modules/macos-release/index.js:26
        const [name, version] = nameMap.get(release);
                                ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/Users/nspehler/.npm/_npx/89d7643beec8fcc5/node_modules/macos-release/index.js:26:26)
    at osName (/Users/nspehler/.npm/_npx/89d7643beec8fcc5/node_modules/os-name/index.js:21:18)
    at new Insight (/Users/nspehler/.npm/_npx/89d7643beec8fcc5/node_modules/insight/lib/index.js:37:13)
    at Object.<anonymous> (/Users/nspehler/.npm/_npx/89d7643beec8fcc5/node_modules/yo/lib/cli.js:54:17)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

Could you please help?

Thank you,
Nicolas

**Comment by stefanoverna** [comment]
Hi! Can you share the result of running `npx -v` and `node -v` in your console please?

**Comment by altjz** [comment]
https://github.com/yeoman/yo/issues/683
